import Head from 'next/head'
import {useState} from 'react'
import dynamic from 'next/dynamic'

const TreeComponent = dynamic(() => import('../components/TreeComponent'), {
    ssr: false
})

export default function Home() {
    const [data, setData] = useState(
        {
            "name": "All Cryptos",
            "children": [
                {
                    "name": "Bitcoin"
                },
                {
                    "name": "Etherium"
                },
                {
                    "name": "Polkadot"
                },
                {
                    "name": "POW",
                    "children": [
                        {
                            "name": "Bitcoin"
                        },
                        {
                            "name": "Litecoin"
                        },
                        {
                            "name": "Bitcoin Cash"
                        }
                    ]
                },
                {
                    "name": "Public Chains",
                    "children": [
                        {
                            "name": "Ripple"
                        },
                        {
                            "name": "Chainlink"
                        },
                        {
                            "name": "POW",
                            "children": [
                                {
                                    "name": "Bitcoin"
                                },
                                {
                                    "name": "Litecoin"
                                },
                                {
                                    "name": "Bitcoin Cash"
                                }
                            ]
                        },
                        {
                            "name": "POS",
                            "children": [
                                {
                                    "name": "Etherium"
                                },
                                {
                                    "name": "EOS"
                                },
                                {
                                    "name": "Crosschain",
                                    "children": [
                                        {
                                            "name": "Polkadot"
                                        },
                                        {
                                            "name": "Cosmos"
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    )

    const onTreeStateChange = (state, e) => console.log({state, e});

    return (
        <>
            <Head>
                <title>Shopino Task</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={'w-full min-h-screen flex flex-col pb-10'}>
                <div className={'w-[90%] mx-auto my-10 rounded p-2 flex justify-center items-center text-blue border-4 border-blue-700'}>
                    Tip: By clicking on the Name of each item, toolbar will be shown
                </div>
                <TreeComponent data={data} onChange={onTreeStateChange}/>
            </div>
        </>
    )
}
